services:
  dns:
    image: dns:${TAG}
    ports:
      - 53:53/udp
    environment:
      - PORT=53
      - RESOLVER_IP=1.1.1.1
      - RESOLVER_PORT=53
      - DEBUG=1
    command: /dns
  rest:
    image: rest:${TAG}
    ports:
      - 8080:8080/tcp
    command: /rest
  mongo:
    image: mongo:4.4.11-rc1-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017/tcp
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:



