FROM golang:latest as build

ARG TARGETOS
ARG TARGETARCH
ARG APP_NAME

ENV WORKDIR ${GOPATH}/${APP_NAME}/
ENV CGO_ENABLED=0

WORKDIR $WORKDIR

COPY go.* $WORKDIR
RUN go mod download
COPY . $WORKDIR

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /${APP_NAME} cmd/${APP_NAME}/main.go

FROM scratch AS bin
ARG APP_NAME
COPY --from=build /${APP_NAME} /
COPY blocked.txt /
