services:
  dns:
    image: dns:${TAG}
    ports:
      - 8090:8090/udp
    environment:
      - PORT=8090
      - RESOLVER_IP=1.1.1.1
      - RESOLVER_PORT=53
    command: /dns
  rest:
    image: rest:${TAG}
    ports:
      - 8080:8080/tcp
    command: /rest


